//! zero-gate -- the quality gates, owned by the repository rather than by the platform.
//!
//! ## Why this exists
//! The gates were wired through `.pre-commit-config.yaml`, a file GENERATED by `git-hooks.nix`
//! whose every entry is an absolute `/nix/store` path. On any machine without that store the
//! entries do not resolve, and pre-commit SKIPS hooks it cannot find -- so all four gates would
//! vanish silently on a new distro. Worse, the file is generated: it cannot simply be edited,
//! because the Nix build rewrites it, and off NixOS nothing regenerates it at all.
//!
//! ⭐ THE LOGIC WAS ALREADY PORTABLE. `flake.nix` says so in its own comment -- "the script is a
//! real file (nix/lib/risk-gate.sh) rather than a string inside a string" -- so the gates are
//! plain bash in the repo and only the WIRING was Nix. This binary is that wiring, in a form the
//! repository owns.
//!
//! ## The rule this inherits
//! ⚠️ A GATE THAT CANNOT RUN MUST NOT PASS. That is the exact failure this replaces: hooks that
//! quietly disappeared. It is also the defect fixed across the health checks on 2026-08-23 --
//! an empty services table, `0/0 tools deployed (0%)`, `0 intents, all valid` on a machine with no
//! ledger. A missing tool is UNKNOWN, and unknown is not success.
//!
//! ## And it stays quiet
//! `risk-gate.sh` records why: "a gate that fires on every commit is a gate people route around
//! with --no-verify, which is how INT-113 and INT-119 both died." So this prints NOTHING on a
//! clean run and everything on a dirty one. Silence is the success signal.

use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

/// What a gate concluded. ⚠️ FOUR STATES, NOT TWO -- see the module note. `Unknown` exists so a
/// missing tool can be reported as missing instead of being counted as agreement.
#[derive(PartialEq)]
enum Verdict {
    Pass,
    Fail(String),
    Unknown(String),
    Skipped,
}

struct Gate {
    name: &'static str,
    verdict: Verdict,
}

fn c(code: &str, s: &str) -> String {
    // No colour crate, and no colour when piped -- a hook's output is often captured.
    if std::env::var("NO_COLOR").is_ok() || !std::io::IsTerminal::is_terminal(&std::io::stderr()) {
        s.to_string()
    } else {
        format!("\x1b[{code}m{s}\x1b[0m")
    }
}

/// Is this executable on PATH? Reads PATH directly rather than shelling out to `command -v`,
/// because shelling out would assume a shell exists -- an assumption inside a portability tool.
fn has(tool: &str) -> bool {
    let Ok(path) = std::env::var("PATH") else {
        return false;
    };
    std::env::split_paths(&path).any(|d| d.join(tool).is_file())
}

/// The repository root, from git itself. ⭐ NOT from a hardcoded path and NOT from $HOME: this
/// binary must work in any checkout, by any user, at any location. Asking git is the only answer
/// that is true everywhere.
fn repo_root() -> Option<PathBuf> {
    let out = Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8(out.stdout).ok()?;
    Some(PathBuf::from(s.trim()))
}

/// Staged files, newline-separated, as the risk gate expects them.
fn staged_files() -> Vec<String> {
    Command::new("git")
        .args(["diff", "--cached", "--name-only", "--diff-filter=ACMR"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| {
            s.lines()
                .map(str::to_string)
                .filter(|l| !l.is_empty())
                .collect()
        })
        .unwrap_or_default()
}

/// Run one of the repo's own bash gates.
///
/// ⚠️ `set -euo pipefail` IS NOT DECORATION HERE. `writeShellApplication` ran these scripts under
/// exactly those flags, and `risk-gate.sh` carries a comment about a trap that only appears under
/// `set -u` -- a declared-but-empty array reads as UNSET and aborts before any logic runs. Running
/// it any other way would silently change the conditions its author debugged under.
fn run_repo_script(root: &Path, rel: &str, args: &[String]) -> Verdict {
    let script = root.join(rel);
    if !script.exists() {
        return Verdict::Unknown(format!("{rel} not found in this checkout"));
    }
    if !has("bash") {
        return Verdict::Unknown("bash not on PATH".into());
    }
    let mut cmd = Command::new("bash");
    cmd.arg("-euo")
        .arg("pipefail")
        .arg(&script)
        .args(args)
        .current_dir(root);
    match cmd.output() {
        Err(e) => Verdict::Unknown(format!("could not run {rel}: {e}")),
        Ok(o) if o.status.success() => Verdict::Pass,
        Ok(o) => {
            let mut msg = String::from_utf8_lossy(&o.stderr).trim().to_string();
            if msg.is_empty() {
                msg = String::from_utf8_lossy(&o.stdout).trim().to_string();
            }
            if msg.is_empty() {
                msg = format!("exited {}", o.status.code().unwrap_or(-1));
            }
            Verdict::Fail(msg)
        }
    }
}

fn gate_ripsecrets(root: &Path, staged: &[String]) -> Verdict {
    if !has("ripsecrets") {
        return Verdict::Unknown(
            "ripsecrets not installed -- secrets are NOT being checked".into(),
        );
    }
    if staged.is_empty() {
        return Verdict::Skipped;
    }
    match Command::new("ripsecrets")
        .arg("--strict-ignore")
        .args(staged)
        .current_dir(root)
        .output()
    {
        Err(e) => Verdict::Unknown(format!("could not run ripsecrets: {e}")),
        Ok(o) if o.status.success() => Verdict::Pass,
        Ok(o) => Verdict::Fail(String::from_utf8_lossy(&o.stdout).trim().to_string()),
    }
}

/// Format, then RE-STAGE what was formatted.
///
/// ⭐ THE RE-STAGE IS THE WHOLE FEATURE (INT-184). A formatter that rewrites a staged file and then
/// fails the commit makes the author run the same command twice for no reason. Formatting is not a
/// judgement -- there is nothing for a human to decide -- so it fixes and stages, and only a
/// formatter that CANNOT RUN is reported.
fn gate_rustfmt(root: &Path, staged: &[String]) -> Verdict {
    let rs: Vec<&String> = staged.iter().filter(|f| f.ends_with(".rs")).collect();
    if rs.is_empty() {
        return Verdict::Skipped;
    }
    if !has("cargo") {
        return Verdict::Unknown("cargo not on PATH -- formatting NOT checked".into());
    }
    for f in &rs {
        let out = Command::new("cargo")
            .args(["fmt", "--", (*f).as_str()])
            .current_dir(root)
            .output();
        match out {
            Err(e) => return Verdict::Unknown(format!("could not run cargo fmt: {e}")),
            Ok(o) if !o.status.success() => {
                let msg = String::from_utf8_lossy(&o.stderr).trim().to_string();
                return Verdict::Fail(format!("cargo fmt failed on {f}: {msg}"));
            }
            Ok(_) => {}
        }
    }
    let re = Command::new("git")
        .arg("add")
        .args(rs.iter().map(|s| s.as_str()))
        .current_dir(root)
        .status();
    match re {
        Ok(s) if s.success() => Verdict::Pass,
        _ => Verdict::Fail("formatted, but could not re-stage".into()),
    }
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let stage = args.first().map(String::as_str).unwrap_or("pre-commit");

    if stage == "--help" || stage == "-h" {
        eprintln!("zero-gate -- repository-owned quality gates");
        eprintln!();
        eprintln!("  zero-gate pre-commit    secrets, formatting   (default)");
        eprintln!("  zero-gate pre-push      the shell test suite");
        eprintln!("  zero-gate all           everything");
        eprintln!();
        eprintln!("Silent on success. A gate that cannot run reports UNKNOWN and fails the run,");
        eprintln!("because a gate that cannot run must never look like a gate that passed.");
        return ExitCode::SUCCESS;
    }

    let Some(root) = repo_root() else {
        eprintln!("{} not a git repository -- nothing to gate", c("31", "✗"));
        return ExitCode::FAILURE;
    };
    let staged = staged_files();
    let mut gates: Vec<Gate> = Vec::new();

    if stage != "pre-push" {
        gates.push(Gate {
            name: "secrets",
            verdict: gate_ripsecrets(&root, &staged),
        });
        gates.push(Gate {
            name: "formatting",
            verdict: gate_rustfmt(&root, &staged),
        });
    }
    if stage == "pre-push" || stage == "all" {
        gates.push(Gate {
            name: "shell tests",
            verdict: run_repo_script(&root, ".githooks/lib/nsh-test-gate.sh", &[]),
        });
    }

    let mut bad = false;
    for g in &gates {
        match &g.verdict {
            Verdict::Pass | Verdict::Skipped => {}
            Verdict::Fail(why) => {
                bad = true;
                eprintln!("{} {:<12} {}", c("31", "✗"), g.name, why);
            }
            Verdict::Unknown(why) => {
                bad = true;
                eprintln!("{} {:<12} {}", c("33", "?"), g.name, why);
            }
        }
    }

    if bad {
        eprintln!();
        eprintln!(
            "  {}",
            c(
                "2",
                "a gate that could not run is not a gate that passed -- fix or install, then retry"
            )
        );
        return ExitCode::FAILURE;
    }
    ExitCode::SUCCESS
}
