// faelight-docs v2.0.0 — Living Documentation Engine
// INT-145 — Keeps README and welcome message in sync with forest state
//
// BOUNDARY RULE: faelight-release owns README lines 1-37 (dynamic section)
//                faelight-docs owns README lines 38+ (static section)
//                These two tools NEVER cross this boundary.
//
// Commands:
//   sync     — update all docs from forest state
//   check    — show what is out of date (dry run)
//   welcome  — regenerate zshrc welcome message only
//   readme   — regenerate README static section only
//   preview  — show what would change without writing
//   status   — what docs exist, last updated

mod registry;
mod toolgen;
use colored::*;
use std::path::PathBuf;

const BOUNDARY_MARKER: &str = "<!-- END DYNAMIC SECTION -->";
const VERSION: &str = "2.0.0";

fn cmd_command_guide(dry_run: bool) {
    println!("  {} Generating COMMAND-GUIDE.md...", "🌲".normal());
    let top_help = match std::process::Command::new("core").arg("--help").output() {
        Ok(o) => {
            String::from_utf8_lossy(&o.stdout).to_string() + &String::from_utf8_lossy(&o.stderr)
        }
        Err(e) => {
            println!("  Cannot run core: {}", e);
            return;
        }
    };
    let mut domains: Vec<(String, String)> = Vec::new();
    let mut in_commands = false;
    for line in top_help.lines() {
        if line.trim() == "Commands:" {
            in_commands = true;
            continue;
        }
        if in_commands {
            if line.is_empty() || (!line.starts_with(' ') && !line.starts_with('\t')) {
                in_commands = false;
                continue;
            }
            let t = line.trim();
            if t.starts_with("help") {
                continue;
            }
            let parts: Vec<&str> = t.splitn(2, "  ").collect();
            let name = parts[0].trim().to_string();
            let desc = parts
                .get(1)
                .map(|s| s.trim().to_string())
                .unwrap_or_default();
            if !name.is_empty() {
                domains.push((name, desc));
            }
        }
    }
    println!("  {} Found {} domains", "→".dimmed(), domains.len());
    let now = chrono::Local::now().format("%Y-%m-%d").to_string();
    let mut md = format!(
        "# Faelight Forest -- Core Command Reference\n\n**Version:** {}  \n**Generated:** {}  \n**Domains:** {}  \n**Source:** Auto-generated by faelight-docs\n\n---\n\n",
        env!("CARGO_PKG_VERSION"), now, domains.len()
    );
    for (domain, desc) in &domains {
        let domain_help = std::process::Command::new("core")
            .args([domain.as_str(), "--help"])
            .output()
            .map(|o| {
                String::from_utf8_lossy(&o.stdout).to_string() + &String::from_utf8_lossy(&o.stderr)
            })
            .unwrap_or_default();
        md.push_str(&format!("## core {}\n\n", domain));
        if !desc.is_empty() {
            md.push_str(&format!("{}\n\n", desc));
        }
        let mut in_sub = false;
        let mut has_subs = false;
        for line in domain_help.lines() {
            if line.trim() == "Commands:" {
                in_sub = true;
                continue;
            }
            if in_sub {
                if line.is_empty() || (!line.starts_with(' ') && !line.starts_with('\t')) {
                    in_sub = false;
                    continue;
                }
                let t = line.trim();
                if t.starts_with("help") {
                    continue;
                }
                let parts: Vec<&str> = t.splitn(2, "  ").collect();
                let cmd_name = parts[0].trim();
                let cmd_desc = parts.get(1).map(|s| s.trim()).unwrap_or("");
                if !cmd_name.is_empty() {
                    if !has_subs {
                        md.push_str("| Command | Description |\n|---------|-------------|\n");
                        has_subs = true;
                    }
                    md.push_str(&format!(
                        "| `core {} {}` | {} |\n",
                        domain, cmd_name, cmd_desc
                    ));
                }
            }
        }
        if !has_subs {
            md.push_str("*No subcommands.*\n");
        }
        md.push_str("\n---\n\n");
    }
    md.push_str("*Generated by `docs command-guide` -- never edit by hand*\n");
    if dry_run {
        println!(
            "  {} Dry run -- would write {} chars",
            "→".dimmed(),
            md.len()
        );
        println!("{}", &md[..md.len().min(500)]);
    } else {
        let out = core_root().join("docs/COMMAND-GUIDE.md");
        std::fs::write(&out, &md).expect("write failed");
        println!(
            "  {} Written: docs/COMMAND-GUIDE.md ({} domains)",
            "✅".green(),
            domains.len()
        );
    }
}
/// INT-315 Phase 3: generate public docs set -- curated, no internal content
fn cmd_public(dry_run: bool) {
    use std::fs;
    let root = core_root();
    let docs_dir = root.join("docs");
    let public_dir = docs_dir.join("public");

    // Public docs -- curated set, no internal language
    let public_files = [
        ("COMMAND-GUIDE.md", "Command Reference"),
        ("ARCHITECTURE.md", "Architecture"),
        ("PHILOSOPHY.md", "Philosophy"),
        ("NSH-PHILOSOPHY.md", "Shell Philosophy"),
        ("design-system.md", "Design System"),
        ("forest-resilience.md", "Resilience Guide"),
        ("NOVASHELL.md", "Shell Reference"),
    ];

    if dry_run {
        println!("  -> public/ would contain {} docs:", public_files.len());
        for (file, title) in &public_files {
            let src = docs_dir.join(file);
            let exists = if src.exists() { "✅" } else { "❌ missing" };
            println!("     {} {} ({})", exists, title, file);
        }
        return;
    }

    if !public_dir.exists() {
        if let Err(e) = fs::create_dir_all(&public_dir) {
            eprintln!("  ❌ Could not create docs/public/: {}", e);
            return;
        }
    }

    // Generate index.md
    let version = std::fs::read_to_string(faelight_core::paths::version_file())
        .unwrap_or_default()
        .trim()
        .to_string();
    let mut index = format!(
        "# Faelight Forest Documentation\n\n> {}\n\n## Contents\n\n",
        version
    );

    let mut copied = 0usize;
    for (file, title) in &public_files {
        let src = docs_dir.join(file);
        let dst = public_dir.join(file);
        if src.exists() {
            if let Ok(src_content) = fs::read_to_string(&src) {
                // Strip any lines containing internal markers
                let clean: String = src_content
                    .lines()
                    .filter(|l| !l.contains("INT-") || l.contains("INT-") && l.starts_with('#'))
                    .collect::<Vec<_>>()
                    .join("\n");
                let _ = fs::write(&dst, clean);
                index.push_str(&format!("- [{}]({})\n", title, file));
                copied += 1;
            }
        }
    }

    let _ = fs::write(public_dir.join("index.md"), index);
    println!(
        "  {} docs/public/ -- {} docs generated",
        "✅".normal(),
        copied
    );
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let cmd = args.get(1).map(|s| s.as_str()).unwrap_or("help");

    match cmd {
        "--health" | "health" => {
            println!("faelight-docs v{} — healthy", VERSION);
        }
        "sync" => {
            cmd_readme(false);
            verify_links(false);
            cmd_public(false);
            println!("  {} All docs synced", "✅".normal());
        }
        "public" => {
            let dry = args.get(2).map(|s| s == "--dry-run").unwrap_or(false);
            cmd_public(dry);
        }
        "check" => {
            cmd_readme(true);
            verify_links(true);
        }
        "verify-links" | "links" => {
            verify_links(false);
        }
        "readme" => cmd_readme(false),
        "preview" => {
            cmd_readme(true);
        }
        "status" => cmd_status(),
        "record" => {
            let doc = args.get(2).map(|s| s.as_str()).unwrap_or("");
            let note = args.get(3).map(|s| s.as_str()).unwrap_or("");
            cmd_record(doc, note);
        }
        "log" => cmd_log(),
        "why" => {
            let doc = args.get(2).map(|s| s.as_str()).unwrap_or("");
            cmd_why(doc);
        }
        "diff" => cmd_diff(),
        "command-guide" => {
            let dry = args.get(2).map(|s| s == "--dry-run").unwrap_or(false);
            cmd_command_guide(dry);
        }
        "readme-tools" => {
            toolgen::cmd_readme_tools_dryprint();
        }
        "readme-preview" => {
            let name = args.get(2).map(|s| s.as_str()).unwrap_or("");
            toolgen::cmd_preview_one(name);
        }
        "readme-generate" => {
            let dry = args.get(2).map(|s| s == "--dry-run").unwrap_or(false);
            toolgen::cmd_generate(dry);
        }
        "changelog-preview" => {
            let name = args.get(2).map(|s| s.as_str()).unwrap_or("");
            toolgen::cmd_changelog_preview(name);
        }
        "changelog-tools" | "changelog-generate" => {
            let dry = args.get(2).map(|s| s == "--dry-run").unwrap_or(false);
            toolgen::cmd_changelog_generate(dry);
        }
        _ => cmd_help(),
    }
}

fn core_root() -> PathBuf {
    dirs::home_dir().unwrap_or_default().join("0-core")
}

struct ForestState {
    version: String,
    theme: String,
    tool_count: usize,
    intent_complete: usize,
    intent_planned: usize,
    commits: String,
    health: String,
    core_domains: usize,
}

fn gather_state() -> ForestState {
    let root = core_root();

    let version = std::fs::read_to_string(faelight_core::paths::version_file())
        .unwrap_or_else(|_| "unknown".to_string())
        .trim()
        .to_string();

    let changelog =
        std::fs::read_to_string(root.join("faelight/meta/CHANGELOG.md")).unwrap_or_default();
    let theme = changelog
        .lines()
        .find(|l| l.contains(&format!("[{}]", version)))
        .and_then(|l| l.split(" — ").nth(1))
        .and_then(|s| s.split('(').next())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "The Living Forest".to_string());

    // Count registered tools from tools.toml -- the same file the doctor path-resilience
    // check reads, which is the point of the comment that used to be here. They disagreed.
    //
    // ⚠️ THE PATH WAS WRONG AND THE FAILURE WAS SILENT. registry/tools.toml has not existed
    // since INT-061 moved directories under faelight/; the file is at
    // faelight/registry/tools.toml. read_to_string failed, unwrap_or(0) turned that into a
    // confident zero, and faelight-docs sync WROTE 0 custom Rust tools into the front page of
    // the repository -- then printed a green check. Caught 2026-09-02 by reading tools: 0 in
    // its own success line while 26 tools were deployed.
    //
    // A missing registry is not zero tools. It is a fact the generator cannot establish, and
    // writing a number it did not measure is how the README came to state something false.
    let tools_path = faelight_core::paths::core_dir().join("faelight/registry/tools.toml");
    let tool_count = match std::fs::read_to_string(&tools_path) {
        // ⚠️ NOT retired ONES. Fixing the path exposed the predicate: counting every
        // name = line gave 51, and 13 of those entries are RETIRED -- core-diff,
        // faelight-notify and faelight-term among them, two of those retired the same
        // day. The sentence in the README is about tools the forest HAS, so a tool it
        // deliberately removed does not count toward it.
        //
        // Splitting on [[tool]] rather than scanning lines, because retired = true and
        // name = are different lines of the same entry and a line filter cannot relate
        // them. 51 entries, 13 retired, 38 live.
        Ok(t) => t
            .split("[[tool]]")
            .filter(|b| b.contains("name = ") && !b.contains("retired = true"))
            .count(),
        Err(e) => {
            eprintln!(
                "  cannot read {} ({}) -- refusing to write a tool count it did not measure",
                tools_path.display(),
                e
            );
            std::process::exit(1);
        }
    };

    // Count intents by scanning all categories — mirrors doctor check_intents logic
    let (intent_complete, intent_planned) = {
        let intent_dir = faelight_core::paths::intents_dir();
        let categories = [
            "complete",
            "decisions",
            "experiments",
            "philosophy",
            "future",
            "cancelled",
            "deferred",
            "incidents",
            "active",
        ];
        let mut complete = 0usize;
        let mut planned = 0usize;
        for cat in &categories {
            if let Ok(entries) = std::fs::read_dir(intent_dir.join(cat)) {
                for entry in entries.flatten() {
                    if entry.path().extension().map(|e| e == "md").unwrap_or(false) {
                        if let Ok(text) = std::fs::read_to_string(entry.path()) {
                            if text.contains("status: complete") {
                                complete += 1;
                            } else if text.contains("status: planned") {
                                planned += 1;
                            }
                        }
                    }
                }
            }
        }
        (complete, planned)
    };

    let commits = std::fs::read_to_string("/etc/faelight/COMMITS")
        .unwrap_or_default()
        .trim()
        .to_string();

    // Read live health — prefer ~/.cache/faelight/health-status, fall back to state.db cache
    let health = {
        let home = std::env::var("HOME").unwrap_or_default();
        let cache_path = std::path::PathBuf::from(&home).join(".cache/faelight/health-status");
        std::fs::read_to_string(&cache_path)
            .or_else(|_| {
                std::fs::read_to_string(faelight_core::paths::cache_dir().join("health.txt"))
            })
            .unwrap_or_else(|_| "100".to_string())
            .trim()
            .trim_end_matches('%')
            .to_string()
    };

    // ⚠️ THE SAME BUG AS THE TOOL COUNT, IN THE SAME FILE, FROM THE SAME CAUSE. The path
    // was engine/src/domains and the engine has been at faelight/engine since INT-061
    // moved directories. read_dir failed, unwrap_or(0) made it zero, and the README
    // advertised 0+ native domains while 55 directories sat on disk. 57 is what ls counts,
    // because ls counts mod.rs too -- the number in the README is directories.
    //
    // TWO sites computed a path into a directory INT-061 moved. The other six root.join
    // calls in this file are correct -- docs, README.md and link resolution really are
    // relative to the repo root. Counted after writing three from memory and being wrong.
    let domains_path = faelight_core::paths::core_dir().join("faelight/engine/src/domains");
    let core_domains = match std::fs::read_dir(&domains_path) {
        Ok(d) => d.flatten().filter(|e| e.path().is_dir()).count(),
        Err(e) => {
            eprintln!(
                "  cannot read {} ({}) -- refusing to write a domain count it did not measure",
                domains_path.display(),
                e
            );
            std::process::exit(1);
        }
    };

    ForestState {
        version,
        theme,
        tool_count,
        intent_complete,
        intent_planned,
        commits,
        health,
        core_domains,
    }
}

fn cmd_readme(dry_run: bool) {
    let root = core_root();
    let readme_path = root.join("README.md");

    let content = match std::fs::read_to_string(&readme_path) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("  {} Cannot read README: {}", "✗".bright_red(), e);
            return;
        }
    };

    // Find boundary — NEVER touch above it
    let boundary_pos = match content.find(BOUNDARY_MARKER) {
        Some(p) => p + BOUNDARY_MARKER.len(),
        None => {
            eprintln!(
                "  {} Boundary marker not found in README — aborting",
                "✗".bright_red()
            );
            return;
        }
    };

    let state = gather_state();

    // ── Targeted patch strategy ───────────────────────────────────────────────
    // Only patch specific live numbers — never replace prose or structure
    let header = content[..boundary_pos].to_string();
    let mut body = content[boundary_pos..].to_string();

    // 1. Tool count: "68 custom Rust tools"
    let tool_pattern = regex_replace_first(
        &body,
        r"\d+ custom Rust tools",
        &format!("{} custom Rust tools", state.tool_count),
    );
    body = tool_pattern;

    // 2. Domain count: "33+ native domains"
    let domain_pattern = regex_replace_first(
        &body,
        r"\d+\+ native domains",
        &format!("{}+ native domains", state.core_domains),
    );
    body = domain_pattern;

    // 3. Intent count: "104 complete intents"
    let intent_pattern = regex_replace_first(
        &body,
        r"\d+ complete intents",
        &format!("{} complete intents", state.intent_complete),
    );
    body = intent_pattern;

    // 4. Timestamp
    let timestamp = format!(
        "*Auto-generated by faelight-docs v{} — last sync: {}*",
        VERSION,
        chrono::Local::now().format("%Y-%m-%d %H:%M")
    );
    body = if let Some(start) = body.find("*Auto-generated by faelight-docs") {
        let end = body[start..]
            .find('\n')
            .map(|i| start + i)
            .unwrap_or(body.len());
        format!("{}{}{}", &body[..start], timestamp, &body[end..])
    } else {
        format!("{}\n{}\n", body.trim_end(), timestamp)
    };

    let new_content = format!("{}{}", header, body);

    // Data-only diff (ignore timestamp line) — drives check/status
    let data_changed = strip_timestamp(&body) != strip_timestamp(&content[boundary_pos..]);

    // Full diff including timestamp — drives actual write
    if content == new_content {
        println!("  {} README already up to date", "✅".normal());
        return;
    }

    if dry_run {
        if data_changed {
            println!("  {} README would update:", "→".bright_cyan());
            println!(
                "     tools: {}  domains: {}+  intents: {}  version: {}",
                state.tool_count.to_string().bright_white(),
                state.core_domains.to_string().bright_white(),
                state.intent_complete.to_string().bright_white(),
                state.version.bright_green(),
            );
        } else {
            println!("  {} README already up to date", "✅".normal());
        }
    } else {
        match std::fs::write(&readme_path, &new_content) {
            Ok(_) => println!(
                "  {} README updated — tools: {}  domains: {}+  intents: {}",
                "✅".normal(),
                state.tool_count.to_string().bright_white(),
                state.core_domains.to_string().bright_white(),
                state.intent_complete.to_string().bright_white(),
            ),
            Err(e) => eprintln!("  {} Cannot write README: {}", "✗".bright_red(), e),
        }
    }
}

// Strip auto-generated timestamp line for data-only comparisons
fn strip_timestamp(s: &str) -> String {
    s.lines()
        .filter(|l| !l.starts_with("*Auto-generated by faelight-docs"))
        .collect::<Vec<_>>()
        .join("\n")
}

// Simple regex-free pattern replacer for "digits + suffix" patterns
fn regex_replace_first(text: &str, pattern_kind: &str, replacement: &str) -> String {
    // Parse the pattern kind to find prefix digits and literal suffix
    let suffix = match pattern_kind {
        r"\d+ custom Rust tools" => " custom Rust tools",
        r"\d+\+ native domains" => "+ native domains",
        r"\d+ complete intents" => " complete intents",
        _ => return text.to_string(),
    };
    // Find the suffix in text, walk back over preceding digits
    if let Some(suffix_pos) = text.find(suffix) {
        let before = &text[..suffix_pos];
        let digit_start = before
            .rfind(|c: char| !c.is_ascii_digit())
            .map(|i| i + 1)
            .unwrap_or(0);
        format!(
            "{}{}{}",
            &text[..digit_start],
            replacement,
            &text[suffix_pos + suffix.len()..]
        )
    } else {
        text.to_string()
    }
}

fn verify_links(dry_run: bool) -> bool {
    let root = core_root();
    let readme_path = root.join("README.md");
    let content = match std::fs::read_to_string(&readme_path) {
        Ok(c) => c,
        Err(_) => return true,
    };

    let mut broken: Vec<String> = vec![];

    // Scan for markdown links [text](path)
    let mut pos = 0;
    let bytes = content.as_bytes();
    while pos < content.len() {
        if let Some(start) = content[pos..].find("](") {
            let link_start = pos + start + 2;
            if let Some(end) = content[link_start..].find(')') {
                let link = &content[link_start..link_start + end];
                // Only check relative links (not http/https/mailto/#)
                if !link.starts_with("http")
                    && !link.starts_with('#')
                    && !link.starts_with("mailto")
                    && !link.is_empty()
                {
                    let full_path = root.join(link);
                    if !full_path.exists() {
                        broken.push(link.to_string());
                    }
                }
                pos = link_start + end + 1;
            } else {
                break;
            }
        } else {
            break;
        }
        let _ = bytes; // suppress warning
    }

    if broken.is_empty() {
        if !dry_run {
            println!(
                "  {} README links verified — all resolve correctly",
                "✅".normal()
            );
        }
        return true;
    }

    for link in &broken {
        println!(
            "  {} Broken link: {}",
            "✗".bright_red(),
            link.bright_white()
        );
    }
    if dry_run {
        println!(
            "  {} {} broken link(s) found — fix before release",
            "⚠️ ".normal(),
            broken.len()
        );
    }
    false
}

fn cmd_status() {
    let state = gather_state();
    let root = core_root();

    println!();
    println!("  {} faelight-docs status", "📋".normal());
    println!("{}", "  ─────────────────────────────────────".dimmed());
    println!(
        "  {}  v{} — {}",
        "Version:".dimmed(),
        state.version.bright_green(),
        state.theme.dimmed()
    );
    println!(
        "  {}    {}",
        "Tools:".dimmed(),
        state.tool_count.to_string().bright_white()
    );
    println!(
        "  {}  {} complete, {} planned",
        "Intents:".dimmed(),
        state.intent_complete.to_string().bright_white(),
        state.intent_planned.to_string().dimmed()
    );
    println!(
        "  {}  {}",
        "Commits:".dimmed(),
        state.commits.bright_white()
    );
    println!(
        "  {}   {}%",
        "Health:".dimmed(),
        state.health.bright_green()
    );
    println!(
        "  {} {}",
        "Core domains:".dimmed(),
        state.core_domains.to_string().bright_white()
    );
    println!();

    // Check README — use actual diff logic, not shallow version check
    let readme_ok = {
        let readme_path = root.join("README.md");
        if let Ok(content) = std::fs::read_to_string(&readme_path) {
            if let Some(boundary_pos) = content
                .find(BOUNDARY_MARKER)
                .map(|p| p + BOUNDARY_MARKER.len())
            {
                let mut body = content[boundary_pos..].to_string();
                body = regex_replace_first(
                    &body,
                    r"\d+ custom Rust tools",
                    &format!("{} custom Rust tools", state.tool_count),
                );
                body = regex_replace_first(
                    &body,
                    r"\d+\+ native domains",
                    &format!("{}+ native domains", state.core_domains),
                );
                body = regex_replace_first(
                    &body,
                    r"\d+ complete intents",
                    &format!("{} complete intents", state.intent_complete),
                );
                // Compare data only — ignore timestamp line
                let strip = |s: &str| {
                    s.lines()
                        .filter(|l| !l.starts_with("*Auto-generated by faelight-docs"))
                        .collect::<Vec<_>>()
                        .join("\n")
                };
                strip(&content[boundary_pos..]) == strip(&body)
            } else {
                false
            }
        } else {
            false
        }
    };
    println!(
        "  {}      {}",
        "README:".dimmed(),
        if readme_ok {
            "✅ up to date".bright_green().to_string()
        } else {
            "⚠  numbers outdated — run: faelight-docs readme"
                .yellow()
                .to_string()
        }
    );
    println!();
}

fn cmd_record(doc: &str, note: &str) {
    if doc.is_empty() {
        println!(
            "  {} usage: fdocs record <doc-name> [note]",
            "✗".bright_red()
        );
        return;
    }
    registry::ensure_tables();
    registry::record_update(doc, "manual", "human", note);
    println!(
        "  {} recorded: {} -- {}",
        "✅".normal(),
        doc.bright_cyan(),
        if note.is_empty() {
            "manual update".to_string()
        } else {
            note.to_string()
        }
    );
}
fn cmd_log() {
    registry::ensure_tables();
    let Ok(conn) = rusqlite::Connection::open(registry::db_path()) else {
        println!("  {} Cannot open state.db", "✗".bright_red());
        return;
    };
    let mut stmt: rusqlite::Statement = match conn.prepare(
        "SELECT name, action, timestamp, by, note FROM doc_history ORDER BY timestamp DESC LIMIT 20"
    ) {
        Ok(s) => s,
        Err(_) => { println!("  {} No doc history yet", "○".dimmed()); return; }
    };
    let rows: Vec<(String, String, i64, String, String)> = stmt
        .query_map([], |r: &rusqlite::Row| {
            Ok((
                r.get::<_, String>(0)?,
                r.get::<_, String>(1)?,
                r.get::<_, i64>(2)?,
                r.get::<_, String>(3)?,
                r.get::<_, String>(4)?,
            ))
        })
        .map(|rows| rows.filter_map(|x| x.ok()).collect::<Vec<_>>())
        .unwrap_or_default();
    if rows.is_empty() {
        println!(
            "  {} No doc history yet -- run fdocs record to start tracking",
            "○".dimmed()
        );
        return;
    }
    println!();
    println!("  {} Document Update History", "📋".normal());
    println!("  {}", "─".repeat(55).dimmed());
    for (name, action, ts, by, note) in &rows {
        let time = chrono::DateTime::from_timestamp(*ts, 0)
            .map(|t| t.format("%m/%d %H:%M").to_string())
            .unwrap_or_default();
        println!(
            "  {} {:<22} {:<10} {} {}",
            time.dimmed(),
            name.as_str().bright_cyan(),
            action.as_str().bright_white(),
            by.as_str().dimmed(),
            note.as_str().dimmed()
        );
    }
    println!();
}
fn cmd_why(doc: &str) {
    if doc.is_empty() {
        println!("  {} usage: fdocs why <doc-name>", "✗".bright_red());
        return;
    }
    let entry = registry::REGISTRY
        .iter()
        .find(|e| e.name == doc || e.path.ends_with(doc));
    match entry {
        Some(e) => {
            println!();
            println!("  {} {}", "📄".normal(), e.name.bright_cyan());
            println!("  {} Path:    {}", "→".dimmed(), e.path.dimmed());
            println!(
                "  {} Owner:   {}",
                "→".dimmed(),
                e.owner_intent.bright_green()
            );
            println!(
                "  {} Purpose: {}",
                "→".dimmed(),
                e.description.bright_white()
            );
            println!(
                "  {} Auto:    {}",
                "→".dimmed(),
                if e.auto_update {
                    "yes -- fdocs sync will update".bright_green().to_string()
                } else {
                    "no -- manual updates required".yellow().to_string()
                }
            );
            println!();
        }
        None => {
            println!(
                "  {} {} not found in document registry",
                "○".dimmed(),
                doc.bright_yellow()
            );
            println!(
                "  {} Managed docs: {}",
                "→".dimmed(),
                registry::REGISTRY
                    .iter()
                    .map(|e| e.name)
                    .collect::<Vec<_>>()
                    .join(", ")
                    .dimmed()
            );
        }
    }
}
fn cmd_diff() {
    registry::ensure_tables();
    let root = registry::core_root();
    println!();
    println!("  {} Document Drift Check", "🔍".normal());
    println!("  {}", "─".repeat(55).dimmed());
    let Ok(conn) = rusqlite::Connection::open(registry::db_path()) else {
        println!("  {} Cannot open state.db", "✗".bright_red());
        return;
    };
    let mut any_drift = false;
    for entry in registry::REGISTRY {
        let full_path = root.join(entry.path);
        if !full_path.exists() {
            continue;
        }
        let current_checksum = registry::file_checksum(&full_path);
        let stored: Option<String> = conn
            .query_row(
                "SELECT checksum FROM doc_registry WHERE name = ?1",
                rusqlite::params![entry.name],
                |r: &rusqlite::Row| r.get::<_, String>(0),
            )
            .ok();
        match stored {
            Some(s) if s == current_checksum => {
                println!(
                    "  {} {:<25} no drift",
                    "✅".normal(),
                    entry.name.bright_white()
                );
            }
            Some(_) => {
                println!(
                    "  {} {:<25} CHANGED since last record",
                    "⚠️ ".yellow(),
                    entry.name.bright_yellow()
                );
                any_drift = true;
            }
            None => {
                println!(
                    "  {} {:<25} never recorded",
                    "○".dimmed(),
                    entry.name.dimmed()
                );
            }
        }
    }
    if !any_drift {
        println!();
        println!(
            "  {} All tracked documents match their last recorded state",
            "✅".green()
        );
    }
    println!();
}
fn cmd_help() {
    println!();
    println!(
        "  {} {}",
        "📋".normal(),
        "faelight-docs".bright_green().bold()
    );
    println!("  {}", "Living Documentation Engine".dimmed());
    println!("{}", "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━".dimmed());
    println!();
    let cmds = [
        ("sync", "Update all docs from forest state"),
        ("check", "Show what is out of date (dry run)"),
        ("readme", "Regenerate README static section"),
        ("preview", "Preview what would change"),
        ("links", "Verify all README links resolve"),
        ("status", "Show doc sync status"),
    ];
    for (c, d) in &cmds {
        println!("  {:12} {}", c.bright_cyan(), d.dimmed());
    }
    println!();
    println!(
        "  {} faelight-release calls faelight-docs sync automatically",
        "Note:".dimmed()
    );
    println!(
        "  {} README lines 1-37 are owned by faelight-release",
        "     ".dimmed()
    );
    println!();
}
