#!/usr/bin/env python3
"""
INT-230 G1 -- classify novashell's faelight_core coupling by CAPABILITY.

Mechanical and re-runnable. Emits markdown to stdout.

THE PROPERTY THAT MAKES IT STAY FIXED: a paths:: function that is not in
BUCKETS is a hard failure (exit 2). A new coupling site cannot land silently
and be discovered later -- it fails the census the day it appears.

Usage, from the repo root:
    python3 census-core-coupling.py > faelight/rust-tools/novashell/CORE-COUPLING.md
    echo $?
"""

import os
import re
import sys

SRC = "faelight/rust-tools/novashell/src"

# The five capability buckets from INT-230. The classification is the finding,
# so it lives here in the open rather than being inferred at read time.
BUCKETS = {
    "core shell state": [
        "state_db",
        "shell_config",
        "runtime_dir",
        "home",
        # XDG_BIN_HOME or ~/.local/bin -- resolves on a machine with no 0-Core,
        # so no adapter. registry.rs:186 scans it to enumerate tools, which is
        # discovery BEHAVIOUR reading a core-state PATH; that caller goes on
        # G2 split list beside intents_dir. The function is classified by what
        # it resolves to, not by what one caller does with it.
        "bin_dir",
    ],
    "0-Core discovery": [
        "intents_dir",
        "rust_tools_dir",
        "registry_dir",
        "tools_registry",
        "core_root_string",
    ],
    "0-Core observability": [
        "version_file",
        "read_health",
        "changelog_file",
    ],
    "0-Core execution": [
        "daemon_socket",
    ],
    "0-Core UI enrichment": [
        # Deliberately empty. intents_dir splits by CALLER, not by function --
        # prompt.rs reading it is enrichment, digest.rs reading it is discovery.
        # G2 makes that split against the file:line evidence below. Putting a
        # function here now would be a guess wearing a classification.
    ],
}

FN_TO_BUCKET = {}
for bucket, fns in BUCKETS.items():
    for fn in fns:
        if fn in FN_TO_BUCKET:
            print("duplicate function in BUCKETS: " + fn, file=sys.stderr)
            sys.exit(3)
        FN_TO_BUCKET[fn] = bucket

CALL = re.compile(r"paths::([a-z_]+)")
CORE = re.compile(r"faelight_core")


def scan(root):
    """Return (hits, core_lines, bare_paths_lines).

    hits: list of (fn, relpath, lineno, text)
    """
    hits = []
    core_lines = 0
    bare = []
    for dirpath, _dirs, files in os.walk(root):
        for name in sorted(files):
            if not name.endswith(".rs"):
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, root)
            with open(full, "r", encoding="utf-8", errors="replace") as fh:
                for lineno, line in enumerate(fh, 1):
                    if CORE.search(line):
                        core_lines += 1
                    found = CALL.findall(line)
                    if found:
                        for fn in found:
                            hits.append((fn, rel, lineno, line.strip()))
                    elif "paths::" in line:
                        # paths:: with no function name after it -- a use
                        # statement or a re-export. Counted, not classified.
                        bare.append((rel, lineno, line.strip()))
    return hits, core_lines, bare


def main():
    if not os.path.isdir(SRC):
        print("run this from the repo root -- " + SRC + " not found", file=sys.stderr)
        return 3

    hits, core_lines, bare = scan(SRC)

    unknown = sorted({fn for fn, _, _, _ in hits if fn not in FN_TO_BUCKET})

    by_bucket = {}
    for fn, rel, lineno, text in hits:
        bucket = FN_TO_BUCKET.get(fn, "UNCLASSIFIED")
        by_bucket.setdefault(bucket, []).append((fn, rel, lineno, text))

    out = []
    out.append("# INT-230 G1 -- novashell coupling to faelight_core, by capability")
    out.append("")
    out.append("Generated by `census-core-coupling.py`. Re-run and diff; do not hand-edit.")
    out.append("")
    out.append("## Units")
    out.append("")
    out.append("Three different numbers get confused here, so all three are stated:")
    out.append("")
    out.append("- lines mentioning `faelight_core`: **" + str(core_lines) + "**")
    out.append("- classified `paths::<fn>` calls: **" + str(len(hits)) + "**")
    out.append("- bare `paths::` with no function (use statements): **" + str(len(bare)) + "**")
    out.append("")
    out.append("A single line can do more than one of these. The unit G1 counts is the")
    out.append("classified call.")
    out.append("")

    order = [
        "core shell state",
        "0-Core discovery",
        "0-Core observability",
        "0-Core execution",
        "0-Core UI enrichment",
        "UNCLASSIFIED",
    ]

    out.append("## Summary")
    out.append("")
    out.append("| bucket | calls | functions |")
    out.append("| --- | --- | --- |")
    for bucket in order:
        rows = by_bucket.get(bucket, [])
        if not rows and bucket == "0-Core UI enrichment":
            out.append("| " + bucket + " | 0 | (split by caller -- see G2) |")
            continue
        if not rows:
            continue
        fns = sorted({fn for fn, _, _, _ in rows})
        out.append("| " + bucket + " | " + str(len(rows)) + " | " + ", ".join(fns) + " |")
    out.append("")

    out.append("## Evidence")
    out.append("")
    for bucket in order:
        rows = by_bucket.get(bucket, [])
        if not rows:
            continue
        out.append("### " + bucket)
        out.append("")
        for fn in sorted({r[0] for r in rows}):
            calls = [r for r in rows if r[0] == fn]
            out.append("**paths::" + fn + "** -- " + str(len(calls)) + " calls")
            out.append("")
            for _fn, rel, lineno, _text in sorted(calls, key=lambda r: (r[1], r[2])):
                out.append("- `" + rel + ":" + str(lineno) + "`")
            out.append("")

    if bare:
        out.append("### bare paths:: (use statements, not calls)")
        out.append("")
        for rel, lineno, text in bare:
            out.append("- `" + rel + ":" + str(lineno) + "` -- " + text)
        out.append("")

    print("\n".join(out))

    if unknown:
        print("", file=sys.stderr)
        print("CENSUS FAILED -- unclassified paths:: functions found:", file=sys.stderr)
        for fn in unknown:
            print("  paths::" + fn, file=sys.stderr)
        print("", file=sys.stderr)
        print("A new coupling site appeared. Classify it in BUCKETS before it lands,", file=sys.stderr)
        print("or the census stops meaning anything.", file=sys.stderr)
        return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
