//! INT-228 -- faelight-docs document registry
//! Tracks all managed documents with freshness, ownership, and drift detection
use std::path::{Path, PathBuf};
pub struct DocEntry {
    pub name: &'static str,
    pub path: &'static str,
    pub owner_intent: &'static str,
    pub description: &'static str,
    pub auto_update: bool,  // can fdocs sync touch this?
}
pub const REGISTRY: &[DocEntry] = &[
    DocEntry {
        name: "README.md",
        path: "00-meta/README.md",
        owner_intent: "INT-228",
        description: "Primary GitHub README -- forest identity and status",
        auto_update: false,  // DYNAMIC section only -- faelight-release owns that
    },
    DocEntry {
        name: "COMMAND-GUIDE.md",
        path: "docs/COMMAND-GUIDE.md",
        owner_intent: "INT-202",
        description: "Muscle memory reference -- all commands that work today",
        auto_update: false,  // manual updates required for new commands
    },
    DocEntry {
        name: "CHANGELOG.md",
        path: "00-meta/CHANGELOG.md",
        owner_intent: "INT-000",
        description: "Release history -- generated by faelight-release",
        auto_update: true,
    },
    DocEntry {
        name: "ARCHITECTURE.md",
        path: "docs/ARCHITECTURE.md",
        owner_intent: "INT-000",
        description: "System architecture overview",
        auto_update: false,
    },
];
pub fn db_path() -> PathBuf {
    dirs::home_dir().unwrap_or_default()
        .join("0-core/runtime/state.db")
}
pub fn core_root() -> PathBuf {
    dirs::home_dir().unwrap_or_default().join("0-core")
}
pub fn ensure_tables() {
    let conn: rusqlite::Connection = match rusqlite::Connection::open(db_path()) { Ok(c) => c, Err(_) => return };
    let _ = conn.execute_batch("
        CREATE TABLE IF NOT EXISTS doc_registry (
            name        TEXT PRIMARY KEY,
            path        TEXT NOT NULL,
            owner       TEXT NOT NULL,
            last_synced INTEGER NOT NULL DEFAULT 0,
            last_manual INTEGER NOT NULL DEFAULT 0,
            checksum    TEXT NOT NULL DEFAULT '',
            stale       INTEGER NOT NULL DEFAULT 0
        );
        CREATE TABLE IF NOT EXISTS doc_history (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            name        TEXT NOT NULL,
            action      TEXT NOT NULL,
            timestamp   INTEGER NOT NULL,
            by          TEXT NOT NULL DEFAULT 'manual',
            note        TEXT NOT NULL DEFAULT ''
        );
    ");
}
pub fn now_ts() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}
pub fn file_checksum(path: &Path) -> String {
    std::fs::read_to_string(path)
        .map(|c| format!("{:x}", c.len()))  // simple length-based checksum
        .unwrap_or_default()
}
#[allow(dead_code)]
pub fn last_modified(path: &Path) -> i64 {
    path.metadata()
        .and_then(|m| m.modified())
        .map(|t| t.duration_since(std::time::UNIX_EPOCH).unwrap_or_default().as_secs() as i64)
        .unwrap_or(0)
}
pub fn record_update(name: &str, action: &str, by: &str, note: &str) {
    ensure_tables();
    let conn: rusqlite::Connection = match rusqlite::Connection::open(db_path()) { Ok(c) => c, Err(_) => return };
    let now = now_ts();
    let _ = conn.execute(
        "INSERT INTO doc_history (name, action, timestamp, by, note) VALUES (?1, ?2, ?3, ?4, ?5)",
        rusqlite::params![name, action, now, by, note],
    );
    let root = core_root();
    let entry = REGISTRY.iter().find(|e| e.name == name);
    if let Some(e) = entry {
        let full_path = root.join(e.path);
        let checksum = file_checksum(&full_path);
        let _ = conn.execute(
            "INSERT OR REPLACE INTO doc_registry (name, path, owner, last_synced, last_manual, checksum, stale)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, 0)",
            rusqlite::params![name, e.path, e.owner_intent, now, now, checksum],
        );
    }
    // Emit signal
    let payload = format!(r#"{{"doc":"{}","action":"{}"}}"#, name, action);
    let _ = conn.execute(
        "INSERT INTO engine_signals (source, signal_type, payload, weight, created_at)
         VALUES ('faelight-docs', 'doc_synced', ?1, 1.0, ?2)",
        rusqlite::params![payload, now],
    );
}
