[package]
name = "faelight-bar"
version = "5.0.0"
edition = "2021"

[[bin]]
name = "faelight-bar"
path = "src/main.rs"

[dependencies]
smithay-client-toolkit = "0.19"
wayland-client = "0.31"
anyhow = "1.0"
thiserror = "1.0"
chrono = "0.4"
dirs = "5.0"

faelight-core = { path = "../faelight-core" }
wayland-protocols = { workspace = true }

# Font rendering
fontdue = "0.9"
lazy_static = "1.4"
